// Generate the print system into all nineteen family guides.
//
// Writes two things into each guide, both inside markers so the script is idempotent and
// re-runnable — this is a GENERATOR, not a one-time migration. Never hand-edit the block
// it emits; change this script or scripts/guide-print-meta.mjs and re-run.
//
//   1. <link rel="stylesheet" media="print" href="guide-print.css"> in <head>.
//      `media="print"` is why the screen rendering is provably unchanged.
//
//   2. A marked block just inside <body> holding a <style> with the one rule that cannot
//      live in the shared sheet: `.print-invite{display:none}` for SCREEN. (It used to
//      also carry a per-guide `@page{@top-left{...}}` running-header title. s12 Track C
//      removed the running header on the operator's ruling of 2026-08-03, so this block
//      no longer holds anything guide-specific at all — it is kept as the marked,
//      idempotent home for screen-side print-system rules.)
//
// THERE IS NO COVER.  Sprint-11 Track D removed it on the operator's direction of
// 2026-08-02 — "I don't like the idea of a cover page and I don't like any of the PDF
// versions right now." This script used to emit a full-bleed cover page into every guide;
// it no longer emits any, and because the block it writes is MARKED and rewritten in full
// on every run, re-running this script is also what DELETES the covers s10 injected. The
// rest of the s10 system stands: running footer, real page margins, range-only pricing.
// `verify_guide_pages.mjs` asserts no page of any guide PDF is full-bleed, so a cover
// cannot creep back in unnoticed.
//
// THERE IS NO RUNNING HEADER (s12 Track C). Operator, 2026-08-03: "we also do not need a
// header." Both top margin boxes are gone — the constant "Bonney Watson" that lived in
// guide-print.css's @top-right, and the per-guide title this script emitted into @top-left.
// The brand mark returned to the masthead instead, which is what he actually asked for.
// Historical note worth keeping: the title HAD to be emitted per document because Chromium
// 148 implements neither `string-set` nor `string()` (Track P3 probed it directly; the box
// came out empty while `counter(page)`/`counter(pages)` worked). If a running header is
// ever wanted again, that limitation is still the constraint.
//
// `.print-invite{display:none}` lives in this injected block rather than in guide-print.css
// because that sheet is media="print" and therefore cannot say anything about screen.
//
// Run from repo root:  node scripts/build_guide_print_system.mjs [substring ...]
import fs from 'fs';
import path from 'path';
import { ROOT } from './_print-server.mjs';
import { GUIDES } from './guide-print-meta.mjs';
import { elementEnd } from './_html-pluck.mjs';
import { tables, classify, invite, money, EXEMPT, chargeColumn, suppressColumn,
         suppressFeeRows, suppressChips, groupAdjacent, CHIP_EXEMPT } from './guide-price-rule.mjs';


const LINK_START = '<!-- BW:PRINT-CSS:START (generated by scripts/build_guide_print_system.mjs) -->';
const LINK_END = '<!-- BW:PRINT-CSS:END -->';
const BLOCK_START = '<!-- BW:PRINT-SYSTEM:START (generated by scripts/build_guide_print_system.mjs — do not hand-edit) -->';
const BLOCK_END = '<!-- BW:PRINT-SYSTEM:END -->';

// (The HTML-entity decoder and CSS string-token escaper that used to live here existed
// solely to build the per-guide running-header title. The header is gone — s12 Track C —
// and so are they.)

function styleHtml() {
  return [
    '<style>',
    '/* Per-guide print constants. Screen is untouched: the only screen rule here hides',
    '   the generated pricing invitation, which exists solely for the PDF. It must never',
    '   show on screen — the shared sheet is media=print and so cannot say anything about',
    '   screen, which is exactly how the invitation blocks first shipped VISIBLE ON THE',
    '   WEBSITE. */',
    '.print-invite{display:none}',
    '/* The condensed-PDF convention (sprint-16). A `.pdf-summary` block is the SHORT',
    '   version of the section it sits in, written next to the long version so the two',
    '   cannot drift. It is for the `?print=family` PDF only: hidden on screen, hidden in',
    '   an ordinary Ctrl+P print, and shown only by the family rules in guide-print.css §8.',
    '   It is hidden here rather than in the shared sheet for the same reason',
    '   `.print-invite` is: that sheet is media=print and cannot say anything about',
    '   screen. */',
    '/* !important, unlike `.print-invite` above, and not for symmetry: a summary is often a',
    '   <span> inside a list item or a paragraph, and the guides style those — `.charge-list',
    '   span{display:block}` is 0,1,1 and beats a bare class selector outright. Seven summary',
    '   spans shipped VISIBLE ON THE WEBSITE the first time this was written without it, and',
    '   only the screen pixel diff caught them. The family rules in guide-print.css §8a still',
    '   win, because `[data-print-mode="family"] .pdf-summary` is more specific than this. */',
    '.pdf-summary{display:none!important}',
    '/* THERE IS NO RUNNING HEADER. This block used to also emit a per-guide',
    '   `@page{@top-left{content:"Bonney Watson · <title>"}}` — the only reason the guide',
    '   metadata was needed at print time at all. Operator, 2026-08-03: "we also do not',
    '   need a header." Removed; the brand mark went back on the masthead instead (see',
    '   guide-print.css §3). Everything else the shared sheet can express, so this block',
    '   is now one screen-only line and nothing more. */',
    '</style>',
  ].join('\r\n');
}

// The print-selection marker, shared by every guide (sprint-16 Track A).
//
// `?part=` has marked the document since sprint-11 — but it did it from a five-line script
// hand-written into the foot of markers-guide.html, which is why exactly one guide could
// use it. It is emitted here now, so a guide adopting either mechanism needs no script of
// its own, and `?print=` rides along on the same three lines:
//
//     cemetery-property-guide.html?print=family     the condensed, emailable PDF
//     markers-guide.html?part=sizes&print=family    both at once
//
// With no query — which is every visit to the website, and every Ctrl+P a family does on
// one — nothing is set and the whole guide renders and prints. That full-length print is
// the deliberate fallback, not an accident: see docs/PDF_DEBRIEF.md.
//
// The value is whitelisted to lowercase words. It goes into an attribute selector, so a
// query string is not allowed to carry anything else into the DOM.
function modeScript() {
  return [
    '<script>',
    '/* Print selection. `?part=` picks a half of a two-PDF guide; `?print=family` asks for',
    '   the condensed family cut. Both mark <html> so the print stylesheets can select on',
    '   them; neither does anything without the query, so the website and an ordinary',
    '   Ctrl+P are untouched. Generated — see scripts/build_guide_print_system.mjs. */',
    '(function () {',
    '  var q = new URLSearchParams(location.search);',
    '  [["part", "data-print-part"], ["print", "data-print-mode"]].forEach(function (pair) {',
    '    var v = q.get(pair[0]);',
    '    if (v && /^[a-z][a-z0-9-]{0,23}$/.test(v)) document.documentElement.setAttribute(pair[1], v);',
    '  });',
    '})();',
    '<\/script>',
  ].join('\r\n');
}

const filters = process.argv.slice(2);
const guides = filters.length ? GUIDES.filter((g) => filters.some((f) => g.includes(f))) : GUIDES;

let changed = 0;
for (const g of guides) {
  const abs = path.join(ROOT, g);
  let html = fs.readFileSync(abs, 'utf8');
  const before = html;

  // ── 1. the stylesheet link ────────────────────────────────────────────────────
  const linkBlock = `${LINK_START}\r\n<link rel="stylesheet" media="print" href="guide-print.css">\r\n${LINK_END}`;
  if (html.includes(LINK_START)) {
    html = html.replace(new RegExp(LINK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + LINK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), linkBlock);
  } else {
    const i = html.indexOf('</head>');
    if (i < 0) throw new Error(`${g}: no </head>`);
    html = html.slice(0, i) + linkBlock + '\r\n' + html.slice(i);
  }

  // ── 2. the per-guide partial (no cover — see the header) ─────────────────────
  const block = [BLOCK_START, styleHtml(), modeScript(), BLOCK_END].join('\r\n');
  if (html.includes(BLOCK_START)) {
    html = html.replace(new RegExp(BLOCK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + BLOCK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), block);
  } else {
    const m = html.match(/<body[^>]*>/);
    if (!m) throw new Error(`${g}: no <body>`);
    const i = html.indexOf(m[0]) + m[0].length;
    html = html.slice(0, i) + '\r\n' + block + html.slice(i);
  }

  // ── 3. the operator's pricing rule ────────────────────────────────────────────
  // See scripts/guide-price-rule.mjs for the rule and for what it deliberately does not
  // touch. Applied by ATTRIBUTE (`data-print-suppress` on the <table>) plus a generated
  // invitation block, both of which are stripped and re-applied on every run, so the
  // stage is idempotent and the authored markup is recoverable by re-running with the
  // rule off. Screen is untouched: the attribute is styled only inside @media print.
  html = html.replace(/\s+data-print-suppress="[^"]*"/g, '')
             .replace(/<!-- BW:PRICE-RULE:START -->[\s\S]*?<!-- BW:PRICE-RULE:END -->/g, '');

  const applied = [];
  if (!EXEMPT.has(g)) {
    const found = tables(html).map((t) => ({ t, c: classify(t) })).filter((x) => x.c);
    // Adjacent priced tables become ONE group with one invitation spanning them: without
    // this, markers-guide.html printed two near-identical invitation paragraphs stacked on
    // top of each other and vault-guide.html printed three.
    const groups = groupAdjacent(found, html);

    // Splice from the end so earlier offsets stay valid.
    for (let i = groups.length - 1; i >= 0; i--) {
      const gr = groups[i];
      const id = `${g.replace(/(?:-guide)?\.html$/, '')}-${i + 1}`;

      if (gr.kind === 'compare') {
        // Keep the table — its price column IS the ranges. Hide only the charges column.
        const t = gr.tables[0];
        const col = chargeColumn(t.html);
        if (col < 0) continue;
        html = html.slice(0, t.start) + suppressColumn(t.html, col) + html.slice(t.end);
        applied.unshift({ id, kind: 'compare', col });
        continue;
      }

      if (gr.kind === 'fee' && gr.rowsOnly) {
        // The table survives because it also holds a verified range; only its fee rows go.
        // NO invitation here: the full one, and even a compact one, costs more room than
        // the rows it replaces, and urn-gardens-guide.html is a deliberately ONE-page
        // infographic (sprint-08 Track U, operator requirement) — both variants pushed it
        // to two. That guide states its endowment-care and opening-and-closing charges in
        // running prose as well as in the table, so suppressing the rows loses the exact
        // figures without losing the fact that the charges exist, which is the point of the
        // rule. Flagged for the operator in the track report.
        const t = gr.tables[0];
        html = html.slice(0, t.start) + suppressFeeRows(t.html) + html.slice(t.end);
        applied.unshift({ id, kind: 'fee-rows' });
        continue;
      }

      const c = gr.kind === 'price'
        ? { kind: 'price', lo: gr.lo, hi: gr.hi, coherent: gr.coherent }
        : gr.c;
      // Tag every table in the group, then put one invitation in front of the first.
      for (let k = gr.tables.length - 1; k >= 0; k--) {
        const t = gr.tables[k];
        const open = t.html.match(/<table\b[^>]*>/)[0];
        const tagged = open.replace(/>$/, ` data-print-suppress="${gr.kind}">`);
        html = html.slice(0, t.start) + tagged + t.html.slice(open.length) + html.slice(t.end);
      }
      const block = `<!-- BW:PRICE-RULE:START -->${invite('print-invite', id, c)}<!-- BW:PRICE-RULE:END -->`;
      html = html.slice(0, gr.start) + block + html.slice(gr.start);
      applied.unshift({ id, ...c, tables: gr.tables.length });
    }

    // Per-item price chips in product-style cards. Table-level suppression alone left
    // vault-guide.html printing seven exact vault prices immediately above an invitation
    // that claimed to have replaced them — found by rendering the page and looking at it.
    if (!CHIP_EXEMPT.has(g)) {
      const r = suppressChips(html);
      html = r.html;
      if (r.n) {
        // If nothing else on the page already invites the family to ask, put the
        // invitation where the first chip was — otherwise the printed guide simply loses
        // every price and says nothing about how to get one.
        if (!applied.some((a) => a.kind === 'price' || a.kind === 'fee')) {
          // Anchor at a SECTION boundary, never at the chip itself. Injecting at the first
          // chip's own offset dropped the block inside a package card on
          // scattering-guide.html and squashed the card's title into a 60px column — the
          // page-count gate was green and the page was visibly broken.
          // `r.at` is the offset of the first chip, so no earlier insertion has shifted it.
          const anchor = Math.max(
            html.lastIndexOf('<div class="section-wrap"', r.at),
            html.lastIndexOf('<section', r.at));
          // Append INSIDE that section, not beside it. A display:none sibling is still a
          // sibling: the guides style `.section-wrap + .section-wrap{border-top:1px …}`,
          // so a hidden block between two sections deleted a rule line ON THE LIVE SITE.
          // Only the screen pixel diff caught it — three guides, ~30 bytes of PNG each.
          const end = anchor < 0 ? -1 : elementEnd(html, anchor);
          if (end < 0) {
            applied.push({ id: `${g}-chips`, kind: 'chips-no-anchor', n: r.n });
          } else {
            const id = `${g.replace(/(?:-guide)?\.html$/, '')}-chips`;
            const c = { kind: 'price', lo: r.lo, hi: r.hi, coherent: r.coherent };
            const block = `<!-- BW:PRICE-RULE:START -->${invite('print-invite', id, c)}<!-- BW:PRICE-RULE:END -->`;
            html = html.slice(0, end) + block + html.slice(end);
            applied.push({ id, ...c });
          }
        }
        applied.push({ id: `${g}-chips`, kind: 'chips', n: r.n });
      }
    }
  }

  if (html !== before) { fs.writeFileSync(abs, html); changed++; }
  const desc = (a) => a.kind === 'chips' ? `chips(${a.n})`
    : a.kind === 'fee-rows' ? 'fee(rows only - table holds a range)'
    : a.kind === 'compare' ? `compare(hide col ${a.col})`
    : a.kind === 'fee' ? 'fee'
    : a.coherent ? `price(${money(a.lo)}-${money(a.hi)}${a.tables > 1 ? ' x' + a.tables : ''})` : 'price(no range - incoherent)';
  const rule = EXEMPT.has(g) ? 'price rule EXEMPT'
    : applied.length ? applied.map(desc).join(' ')
    : 'no priced tables';
  console.log(`  ${g.padEnd(38)} ${rule}`);
}
console.log(`\n${guides.length} guide(s) processed, ${changed} rewritten`);
