"""
Build all-caskets.html — a combined catalog of every metal + wood casket so families
can browse and compare across both types on one page.

Templated from the LIVE wood-caskets.html (it carries the content-classifier version of
the Compare feature, which handles both metal cards and wood's cloth-covered cards that
omit a Finish line — metal's positional Compare would mislabel those). Metal cards are
pulled from the live metal-caskets.html. Each card is tagged data-cat="metal|wood" to
drive a "Casket Type" facet. Image paths are left untouched (casket-images/metal|wood/…)
and resolve fine since this page lives at the repo root too.

Re-run whenever the metal or wood catalog changes:  python scripts/build_all_caskets.py
Then rebuild the PDF:  node scripts/build_catalog_pdfs.mjs all-caskets
"""
import io, re, sys

# These catalog HTML files use LF line endings (generated by the Python build scripts;
# git has core.autocrlf=true). Normalize to LF on read and write LF back.
def read(p):  return io.open(p, 'r', encoding='utf-8', newline='').read().replace('\r\n', '\n')
def write(p, s): io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('\r\n', '\n'))

CARD_RE = re.compile(r'<div class="product-card"[\s\S]*?</label>\s*</div>\s*</div>')

def cards_from(path, cat):
    s = read(path)
    out = []
    for c in CARD_RE.findall(s):
        c = c.replace('<div class="product-card" ',
                      '<div class="product-card" data-cat="%s" ' % cat, 1)
        price = float(re.search(r'data-price="([\d.]+)"', c).group(1))
        out.append((price, c))
    return out

def main():
    metal = cards_from('metal-caskets.html', 'metal')
    wood  = cards_from('wood-caskets.html',  'wood')
    combined = metal + wood
    combined.sort(key=lambda pc: pc[0])
    n = len(combined)
    prices = [p for p, _ in combined]
    lo, hi = min(prices), max(prices)
    def money(x): return '${:,.2f}'.format(x)
    print('metal=%d wood=%d total=%d  range %s - %s' % (len(metal), len(wood), n, money(lo), money(hi)))

    s = read('wood-caskets.html')   # template

    # ---- swap the product grid ----
    gopen = '<div class="product-grid" id="productGrid">'
    i = s.index(gopen) + len(gopen)
    close = '\n    </div>\n  </div>'
    j = s.index(close, i)
    new_inner = '\n' + '\n'.join('        ' + c for _, c in combined)
    s = s[:i] + new_inner + s[j:]

    # ---- text / label swaps ----
    subs = [
        ('<title>Wood Caskets &middot; Bonney Watson</title>',
         '<title>All Caskets &middot; Bonney Watson</title>'),
        ('<h1>Wood Caskets</h1>', '<h1>All Caskets</h1>'),
        ('Hardwood and veneer caskets from Batesville suitable for burial or cremation — available at Washington Memorial Park.',
         'Every metal and wood casket from Batesville, side by side — filter and compare across both. Available at Washington Memorial Park.'),
        ('<div class="cover-footer">63 caskets &middot; $1,540.00 &ndash; $21,100.00</div>',
         '<div class="cover-footer">%d caskets &middot; %s &ndash; %s</div>' % (n, money(lo), money(hi))),
        ('<span class="filter-count" id="filterCount">63 caskets</span>',
         '<span class="filter-count" id="filterCount">%d caskets</span>' % n),
        ('<div class="ps-eyebrow" id="psEyebrow">Wood Caskets</div>',
         '<div class="ps-eyebrow" id="psEyebrow">Caskets</div>'),
        ('<div class="compare-title">Compare Wood Caskets</div>',
         '<div class="compare-title">Compare Caskets</div>'),
        # Filtered print sheet (s11 Track C): the eyebrow is the only per-catalog
        # value that differs from the wood template — PER_PAGE and SHEET_TITLE are
        # already right for a casket page.
        ('  var SHEET_EYEBROW = "Wood Caskets";',
         '  var SHEET_EYEBROW = "Caskets";'),
    ]
    for a, b in subs:
        if s.count(a) != 1:
            print('  !! substitution anchor not unique: %r (found %d)' % (a[:48], s.count(a))); sys.exit(1)
        s = s.replace(a, b, 1)

    # cover-sub uses an em dash without entity? handle plain '—' fallback
    # (the wood file may use a literal em dash rather than &mdash;)
    # ---- facet config: add Casket Type + Color, relabel Material ----
    # COLOR_LABELS is injected separately, ahead of the shared PRICE_BANDS ladder, so
    # the emitted order matches the hand-maintained pages exactly (COLOR_LABELS ->
    # price helpers -> FACETS). Emitting it as part of the FACETS replacement would
    # reorder it below the price helpers and break the byte-identical round-trip.
    color_labels = ('  var COLOR_LABELS = { white:\'White\', ivory:\'Ivory / Champagne\', silver:\'Silver\', grey:\'Grey / Pewter\', black:\'Black\', blue:\'Blue\', green:\'Green\', purple:\'Purple\', pink:\'Pink / Rose\', red:\'Red / Burgundy\', brown:\'Brown / Copper\', gold:\'Gold\' };\n')
    price_anchor = '  // Price bands. One ladder covers every catalog'
    if s.count(price_anchor) != 1:
        print('  !! price-helpers anchor not unique (found %d)' % s.count(price_anchor)); sys.exit(1)
    s = s.replace(price_anchor, color_labels + price_anchor, 1)
    combined_facets = ('  var FACETS = [\n'
                        "    { key:'cremation', label:'Cremation', value:function(card){ return card.getAttribute('data-cremation')||''; } },\n"
                        "    { key:'cat',      label:'Casket Type', value:function(card){ var c=card.getAttribute('data-cat')||''; return c ? c.charAt(0).toUpperCase()+c.slice(1) : ''; } },\n"
                        "    { key:'material', label:'Material', value:firstDetail },\n"
                        "    { key:'fabric',   label:'Interior Fabric', value:fabric },\n"
                        "    { key:'color',    label:'Color', value:function(card){ var c=card.getAttribute('data-color')||''; return c ? (COLOR_LABELS[c]||c) : ''; } },\n"
                        "    { key:'price', label:'Price', value:priceBand, order:PRICE_ORDER }\n"
                        '  ];')
    # The wood block's FIRST facet has changed twice (wood -> cremation, 2026-07-30);
    # anchor on the block opener and its trailing "];" instead of on whichever facet
    # happens to lead, so adding a facet to wood cannot silently break this builder.
    facet_pat = re.compile(r"  var FACETS = \[\r?\n[\s\S]*?\r?\n  \];")
    if len(facet_pat.findall(s)) != 1:
        print('  !! wood FACETS block not matched uniquely (found %d)' % len(facet_pat.findall(s))); sys.exit(1)
    s = facet_pat.sub(lambda m: combined_facets, s, count=1)

    write('all-caskets.html', s)
    print('wrote all-caskets.html')

if __name__ == '__main__':
    sys.stdout.reconfigure(encoding='utf-8')
    main()
