// Generate the print system into all nineteen family guides.
//
// Writes two things into each guide, both inside markers so the script is idempotent and
// re-runnable — this is a GENERATOR, not a one-time migration. Never hand-edit the block
// it emits; change this script or scripts/guide-print-meta.mjs and re-run.
//
//   1. <link rel="stylesheet" media="print" href="guide-print.css"> in <head>.
//      `media="print"` is why the screen rendering is provably unchanged.
//
//   2. A marked block just inside <body> holding a <style> with the per-guide constants
//      that cannot live in the shared sheet: the @page @top-left title string, and
//      `.print-invite{display:none}` for screen.
//
// THERE IS NO COVER.  Sprint-11 Track D removed it on the operator's direction of
// 2026-08-02 — "I don't like the idea of a cover page and I don't like any of the PDF
// versions right now." This script used to emit a full-bleed cover page into every guide;
// it no longer emits any, and because the block it writes is MARKED and rewritten in full
// on every run, re-running this script is also what DELETES the covers s10 injected. The
// rest of the s10 system stands: running footer, real page margins, range-only pricing.
// `verify_guide_pages.mjs` asserts no page of any guide PDF is full-bleed, so a cover
// cannot creep back in unnoticed.
//
// WHY THE TITLE IS A PER-GUIDE CONSTANT. A running header would normally use
// `string-set: doc-title content()` on the masthead and `content: string(doc-title)` in
// the margin box. Chromium 148 does not implement `string-set`/`string()` — Track P3's
// probe tested it directly and the box came out empty, while `counter(page)` and
// `counter(pages)` in the same probe worked. So the title is emitted per document. The
// copy still comes from the guide's own masthead (see guide-print-meta.mjs), so it cannot
// drift from the page.
//
// `.print-invite{display:none}` lives in this injected block rather than in guide-print.css
// because that sheet is media="print" and therefore cannot say anything about screen.
//
// Run from repo root:  node scripts/build_guide_print_system.mjs [substring ...]
import fs from 'fs';
import path from 'path';
import { ROOT } from './_print-server.mjs';
import { extract, GUIDES } from './guide-print-meta.mjs';
import { elementEnd } from './_html-pluck.mjs';
import { tables, classify, invite, money, EXEMPT, chargeColumn, suppressColumn,
         suppressFeeRows, suppressChips, groupAdjacent, CHIP_EXEMPT } from './guide-price-rule.mjs';


const LINK_START = '<!-- BW:PRINT-CSS:START (generated by scripts/build_guide_print_system.mjs) -->';
const LINK_END = '<!-- BW:PRINT-CSS:END -->';
const BLOCK_START = '<!-- BW:PRINT-SYSTEM:START (generated by scripts/build_guide_print_system.mjs — do not hand-edit) -->';
const BLOCK_END = '<!-- BW:PRINT-SYSTEM:END -->';

const ENT = { '&amp;': '&', '&mdash;': '—', '&ndash;': '–', '&middot;': '·',
              '&rsquo;': '’', '&lsquo;': '‘', '&nbsp;': ' ', '&quot;': '"',
              '&ldquo;': '“', '&rdquo;': '”', '&lt;': '<', '&gt;': '>' };
const decode = (s) => s.replace(/&[a-z]+;/g, (m) => ENT[m] ?? m);

// A CSS string token: escape backslash and quote, and keep it on one line.
const cssStr = (s) => '"' + decode(s).replace(/[\\"]/g, (c) => '\\' + c).replace(/\s+/g, ' ').trim() + '"';

function styleHtml(m) {
  return [
    '<style>',
    '/* Per-guide print constants. Screen is untouched: the only screen rule here hides',
    '   the generated pricing invitation, which exists solely for the PDF. It must never',
    '   show on screen — the shared sheet is media=print and so cannot say anything about',
    '   screen, which is exactly how the invitation blocks first shipped VISIBLE ON THE',
    '   WEBSITE. */',
    '.print-invite{display:none}',
    '@media print{',
    '  @page{ @top-left{ content:' + cssStr('Bonney Watson · ' + m.title) + ';',
    "           font-family:'Source Sans 3',sans-serif; font-size:7.5pt; color:#6a7686; letter-spacing:.05em; } }",
    '  /* Page 1 opens under the guide\'s own masthead, which states the title an inch',
    '     below in 16pt. Repeating it in the running header would be the only thing on',
    '     the page said twice. Every other page keeps it. */',
    '  @page :first{ @top-left{content:none} }',
    '}',
    '</style>',
  ].join('\r\n');
}

const filters = process.argv.slice(2);
const guides = filters.length ? GUIDES.filter((g) => filters.some((f) => g.includes(f))) : GUIDES;

let changed = 0;
for (const g of guides) {
  const abs = path.join(ROOT, g);
  let html = fs.readFileSync(abs, 'utf8');
  const before = html;
  const meta = extract(g);

  // The title is the running header on every page after the first, so an empty one is a
  // shipped defect: it means the masthead markup changed shape and every printed page
  // would carry a blank header box.
  if (!meta.title) throw new Error(`${g}: no masthead title found — the running header cannot be derived`);

  // ── 1. the stylesheet link ────────────────────────────────────────────────────
  const linkBlock = `${LINK_START}\r\n<link rel="stylesheet" media="print" href="guide-print.css">\r\n${LINK_END}`;
  if (html.includes(LINK_START)) {
    html = html.replace(new RegExp(LINK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + LINK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), linkBlock);
  } else {
    const i = html.indexOf('</head>');
    if (i < 0) throw new Error(`${g}: no </head>`);
    html = html.slice(0, i) + linkBlock + '\r\n' + html.slice(i);
  }

  // ── 2. the per-guide partial (no cover — see the header) ─────────────────────
  const block = [BLOCK_START, styleHtml(meta), BLOCK_END].join('\r\n');
  if (html.includes(BLOCK_START)) {
    html = html.replace(new RegExp(BLOCK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + BLOCK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), block);
  } else {
    const m = html.match(/<body[^>]*>/);
    if (!m) throw new Error(`${g}: no <body>`);
    const i = html.indexOf(m[0]) + m[0].length;
    html = html.slice(0, i) + '\r\n' + block + html.slice(i);
  }

  // ── 3. the operator's pricing rule ────────────────────────────────────────────
  // See scripts/guide-price-rule.mjs for the rule and for what it deliberately does not
  // touch. Applied by ATTRIBUTE (`data-print-suppress` on the <table>) plus a generated
  // invitation block, both of which are stripped and re-applied on every run, so the
  // stage is idempotent and the authored markup is recoverable by re-running with the
  // rule off. Screen is untouched: the attribute is styled only inside @media print.
  html = html.replace(/\s+data-print-suppress="[^"]*"/g, '')
             .replace(/<!-- BW:PRICE-RULE:START -->[\s\S]*?<!-- BW:PRICE-RULE:END -->/g, '');

  const applied = [];
  if (!EXEMPT.has(g)) {
    const found = tables(html).map((t) => ({ t, c: classify(t) })).filter((x) => x.c);
    // Adjacent priced tables become ONE group with one invitation spanning them: without
    // this, markers-guide.html printed two near-identical invitation paragraphs stacked on
    // top of each other and vault-guide.html printed three.
    const groups = groupAdjacent(found, html);

    // Splice from the end so earlier offsets stay valid.
    for (let i = groups.length - 1; i >= 0; i--) {
      const gr = groups[i];
      const id = `${g.replace(/(?:-guide)?\.html$/, '')}-${i + 1}`;

      if (gr.kind === 'compare') {
        // Keep the table — its price column IS the ranges. Hide only the charges column.
        const t = gr.tables[0];
        const col = chargeColumn(t.html);
        if (col < 0) continue;
        html = html.slice(0, t.start) + suppressColumn(t.html, col) + html.slice(t.end);
        applied.unshift({ id, kind: 'compare', col });
        continue;
      }

      if (gr.kind === 'fee' && gr.rowsOnly) {
        // The table survives because it also holds a verified range; only its fee rows go.
        // NO invitation here: the full one, and even a compact one, costs more room than
        // the rows it replaces, and urn-gardens-guide.html is a deliberately ONE-page
        // infographic (sprint-08 Track U, operator requirement) — both variants pushed it
        // to two. That guide states its endowment-care and opening-and-closing charges in
        // running prose as well as in the table, so suppressing the rows loses the exact
        // figures without losing the fact that the charges exist, which is the point of the
        // rule. Flagged for the operator in the track report.
        const t = gr.tables[0];
        html = html.slice(0, t.start) + suppressFeeRows(t.html) + html.slice(t.end);
        applied.unshift({ id, kind: 'fee-rows' });
        continue;
      }

      const c = gr.kind === 'price'
        ? { kind: 'price', lo: gr.lo, hi: gr.hi, coherent: gr.coherent }
        : gr.c;
      // Tag every table in the group, then put one invitation in front of the first.
      for (let k = gr.tables.length - 1; k >= 0; k--) {
        const t = gr.tables[k];
        const open = t.html.match(/<table\b[^>]*>/)[0];
        const tagged = open.replace(/>$/, ` data-print-suppress="${gr.kind}">`);
        html = html.slice(0, t.start) + tagged + t.html.slice(open.length) + html.slice(t.end);
      }
      const block = `<!-- BW:PRICE-RULE:START -->${invite('print-invite', id, c)}<!-- BW:PRICE-RULE:END -->`;
      html = html.slice(0, gr.start) + block + html.slice(gr.start);
      applied.unshift({ id, ...c, tables: gr.tables.length });
    }

    // Per-item price chips in product-style cards. Table-level suppression alone left
    // vault-guide.html printing seven exact vault prices immediately above an invitation
    // that claimed to have replaced them — found by rendering the page and looking at it.
    if (!CHIP_EXEMPT.has(g)) {
      const r = suppressChips(html);
      html = r.html;
      if (r.n) {
        // If nothing else on the page already invites the family to ask, put the
        // invitation where the first chip was — otherwise the printed guide simply loses
        // every price and says nothing about how to get one.
        if (!applied.some((a) => a.kind === 'price' || a.kind === 'fee')) {
          // Anchor at a SECTION boundary, never at the chip itself. Injecting at the first
          // chip's own offset dropped the block inside a package card on
          // scattering-guide.html and squashed the card's title into a 60px column — the
          // page-count gate was green and the page was visibly broken.
          // `r.at` is the offset of the first chip, so no earlier insertion has shifted it.
          const anchor = Math.max(
            html.lastIndexOf('<div class="section-wrap"', r.at),
            html.lastIndexOf('<section', r.at));
          // Append INSIDE that section, not beside it. A display:none sibling is still a
          // sibling: the guides style `.section-wrap + .section-wrap{border-top:1px …}`,
          // so a hidden block between two sections deleted a rule line ON THE LIVE SITE.
          // Only the screen pixel diff caught it — three guides, ~30 bytes of PNG each.
          const end = anchor < 0 ? -1 : elementEnd(html, anchor);
          if (end < 0) {
            applied.push({ id: `${g}-chips`, kind: 'chips-no-anchor', n: r.n });
          } else {
            const id = `${g.replace(/(?:-guide)?\.html$/, '')}-chips`;
            const c = { kind: 'price', lo: r.lo, hi: r.hi, coherent: r.coherent };
            const block = `<!-- BW:PRICE-RULE:START -->${invite('print-invite', id, c)}<!-- BW:PRICE-RULE:END -->`;
            html = html.slice(0, end) + block + html.slice(end);
            applied.push({ id, ...c });
          }
        }
        applied.push({ id: `${g}-chips`, kind: 'chips', n: r.n });
      }
    }
  }

  if (html !== before) { fs.writeFileSync(abs, html); changed++; }
  const desc = (a) => a.kind === 'chips' ? `chips(${a.n})`
    : a.kind === 'fee-rows' ? 'fee(rows only - table holds a range)'
    : a.kind === 'compare' ? `compare(hide col ${a.col})`
    : a.kind === 'fee' ? 'fee'
    : a.coherent ? `price(${money(a.lo)}-${money(a.hi)}${a.tables > 1 ? ' x' + a.tables : ''})` : 'price(no range - incoherent)';
  const rule = EXEMPT.has(g) ? 'price rule EXEMPT'
    : applied.length ? applied.map(desc).join(' ')
    : 'no priced tables';
  console.log(`  ${g.padEnd(38)} ${rule}`);
}
console.log(`\n${guides.length} guide(s) processed, ${changed} rewritten`);
