/**
 * Gate for the Eternal Light Columbarium niche map.
 *
 * Proves that MAPS/ECL_NicheMap.html is a faithful, deterministic rendering of
 * scripts/ecl-niche-data.mjs, and — the part that matters in front of a family —
 * that NOT ONE dollar figure is rendered for a niche that cannot be sold.
 *
 *   node scripts/verify_ecl_map.mjs
 *
 * Exit 1 on any failure. Sabotage a price or a status in the data module and this
 * must go red.
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {
  WALLS, FACE_ORDER, FACE_META, ROWS, TIERS, FEES, allNiches, refOf, sellable,
} from './ecl-niche-data.mjs';
import { MOVEMENT_TOKENS } from './map-movement.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REL = 'MAPS/ECL_NicheMap.html';
const ABS = path.join(ROOT, REL);

// The sheet's OWN printed COUNT fields. Not derived from the data module — typed from
// the price sheet, so a transcription that drops or duplicates a cell fails here.
const SHEET_COUNT = { S: 31, N: 30, W: 12, E: 12 };
const SHEET_TOTAL = 85;

// ── AVAILABILITY ANCHORS — operator MIS list, 2026-08-01 ──────────────────────
// Typed from the operator's list, NOT derived from the data module, so a niche that
// silently flips status fails here. The list carried 21 niches; the 7 that had been
// available on the July sheet and were absent from it have sold. Previous anchors
// (July sheet): 28 available, $685,175 — S 14/$353,035 · N 8/$226,570 · W 5/$84,675 ·
// E 1/$20,895. The seven that sold: S-D-2 $32,995, S-B-6 $15,395, N-D-1 $28,595,
// N-C-5 $26,395, W-C-1 $18,695, W-B-2 $14,295, W-A-1 $12,095 — which is exactly the
// $148,465 the whole-cabinet total drops by.
const N_AVAIL = 21;
const AVAIL_ANCHOR = 536710;
const PER_FACE_ANCHOR = { S: [12, 304645], N: [6, 171580], W: [2, 39590], E: [1, 20895] };

let failures = 0;
const fail = (m) => { failures++; console.log('  FAIL  ' + m); };
const pass = (m) => console.log('  ok    ' + m);
const ck = (ok, m) => (ok ? pass : fail)(m);
const money = (n) => '$' + n.toLocaleString('en-US');

console.log('\nEternal Light Columbarium (ECL-1) niche-map gate\n');

// ── 0. Every price has a tier (checked first: without it the build throws) ────
console.log('Data module');
{
  const orphan = [...new Set(allNiches().filter(sellable).map((n) => n.p))]
    .filter((p) => !TIERS.some((t) => t.p === p));
  ck(orphan.length === 0, `every price has a colour tier${orphan.length ? ' — orphans: ' + orphan.join(', ') : ` (${TIERS.length} tiers)`}`);
  const ghost = TIERS.map((t) => t.p).filter((p) => !allNiches().some((n) => sellable(n) && n.p === p));
  ck(ghost.length === 0, `no tier is defined for a price that no niche carries${ghost.length ? ' — ' + ghost.join(', ') : ''}`);
  const priced = allNiches().filter((n) => n.st !== 'available' && n.p !== null);
  ck(priced.length === 0, `no unsellable niche carries a price in the data${priced.length ? ' — ' + priced.map((n) => n.ref).join(', ') : ' (the sheet prints none)'}`);
  // An 'available' niche with no price would render as a blank cell — no chip, no
  // status badge — and read as sellable at an unknown price. That is the worst cell on
  // the page, so it is a hard failure rather than a silent blank.
  const blank = allNiches().filter((n) => n.st === 'available' && typeof n.p !== 'number');
  ck(blank.length === 0, `every available niche has a price${blank.length ? ' — ' + blank.map((n) => n.ref).join(', ') : ''}`);
  const known = new Set(['available', 'sold', 'unpriced']);
  const oddSt = allNiches().filter((n) => !known.has(n.st));
  ck(oddSt.length === 0, `every status is one of available / sold / unpriced${oddSt.length ? ' — ' + oddSt.map((n) => n.ref + ':' + n.st).join(', ') : ''}`);
}
if (failures) { console.log(`\nRESULT: ${failures} FAILURE(S) — the page cannot be built from this data`); process.exit(1); }

// ── 1. Build determinism ──────────────────────────────────────────────────────
console.log('\nBuild determinism');
{
  const before = fs.readFileSync(ABS);
  execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'build_ecl_map.mjs')], { cwd: ROOT, stdio: 'pipe' });
  const after = fs.readFileSync(ABS);
  ck(before.equals(after),
    `rebuilding from scripts/ecl-niche-data.mjs reproduces ${REL} byte for byte (${after.length} bytes)`);
}
const src = fs.readFileSync(ABS, 'utf8');
ck(/Generated by scripts\/build_ecl_map\.mjs/.test(src), 'the page declares its generator and says not to hand-edit');

// ── 2. Structural integrity of the transcription ──────────────────────────────
console.log('\nTranscription structure (data module)');
for (const f of FACE_ORDER) {
  const W = WALLS[f];
  const total = W.cols.length;
  // Every row must tile its face exactly once: no gap, no overlap. This is what
  // catches a mistyped column start or span.
  const grid = ROWS.map(() => new Array(total).fill(0));
  for (const n of W.niches) {
    const rEnd = ROWS.indexOf(n.r);
    for (let r = rEnd - ((n.h || 1) - 1); r <= rEnd; r++) {
      for (let c = n.c - 1; c < n.c - 1 + n.w; c++) {
        if (r < 0 || c < 0 || c >= total) { grid[Math.max(0, r)][0] = 99; continue; }
        grid[r][c] += 1;
      }
    }
  }
  const bad = [];
  grid.forEach((row, ri) => row.forEach((v, ci) => { if (v !== 1) bad.push(`${ROWS[ri]}@col${ci + 1}=${v}`); }));
  ck(bad.length === 0, `${FACE_META[f].label.padEnd(14)} ${ROWS.length}×${total} cell grid tiles exactly once ${bad.length ? '— ' + bad.slice(0, 6).join(' ') : ''}`);
}

// ── 3. Counts vs the sheet's printed COUNT fields ─────────────────────────────
console.log("\nPer-face counts vs the price sheet's own printed COUNT");
function parseButtons(cls) {
  const out = [];
  const re = new RegExp(`<button[^>]*class="${cls}[^"]*"[^>]*>[\\s\\S]*?</button>`, 'g');
  for (const m of src.matchAll(re)) {
    const html = m[0];
    const tag = html.slice(0, html.indexOf('>') + 1);
    const at = (k) => { const r = new RegExp(`data-${k}="([^"]*)"`).exec(tag); return r ? r[1] : null; };
    if (at('ref') === null) continue;
    out.push({ face: at('face'), id: at('id'), ref: at('ref'), price: at('price'), st: at('st'), html });
  }
  return out;
}
const from3d = parseButtons('n3 front3');
const fromFlat = parseButtons('n flatn');
const flatFull = [], flatMini = [];
{
  const seen = new Set();
  for (const c of fromFlat) { (seen.has(c.ref) ? flatMini : flatFull).push(c); seen.add(c.ref); }
}
const data = allNiches();

for (const f of FACE_ORDER) {
  const d = WALLS[f].niches.length;
  const a = from3d.filter((c) => c.face === f).length;
  const b = flatFull.filter((c) => c.face === f).length;
  const c = flatMini.filter((c) => c.face === f).length;
  ck([d, a, b, c].every((v) => v === SHEET_COUNT[f]),
    `${FACE_META[f].label.padEnd(14)} sheet ${SHEET_COUNT[f]}  data ${d}  3D ${a}  flat ${b}  overview ${c}`);
}
ck([data.length, from3d.length, flatFull.length, flatMini.length].every((v) => v === SHEET_TOTAL),
  `total = ${SHEET_TOTAL} in the data module, the 3D faces, the flat grids and the overview ` +
  `(${[data.length, from3d.length, flatFull.length, flatMini.length].join('/')})`);

// ── 4. Refs ───────────────────────────────────────────────────────────────────
console.log('\nReferences');
{
  const pat = /^ECL-1-[SNWE]-[A-F]-\d+$/;
  const badPat = data.filter((n) => !pat.test(n.ref));
  ck(badPat.length === 0, `all ${data.length} refs match ECL-1-<S|N|W|E>-<row>-<n>${badPat.length ? ' — ' + badPat.slice(0, 5).map((n) => n.ref).join(', ') : ''}`);
  const seen = new Map();
  const dup = [];
  for (const n of data) { if (seen.has(n.ref)) dup.push(n.ref); seen.set(n.ref, 1); }
  ck(dup.length === 0, `all ${data.length} refs unique${dup.length ? ' — dupes: ' + dup.join(', ') : ''}`);
  const rendered = new Set(from3d.map((c) => c.ref));
  const missing = data.filter((n) => !rendered.has(n.ref)).map((n) => n.ref);
  ck(missing.length === 0, `every data-module ref is rendered in the 3D scene${missing.length ? ' — missing ' + missing.slice(0, 5).join(', ') : ''}`);
  ck(from3d.every((c) => c.ref === refOf(c.face, c.ref.split('-')[3], +c.ref.split('-')[4])),
    'every rendered ref is self-consistent with its face/row/number attributes');
}

// ── 5. Price multiset + available total ───────────────────────────────────────
console.log('\nPrices');
const dataPrices = data.filter(sellable).map((n) => n.p).sort((a, b) => a - b);
const AVAIL_TOTAL = dataPrices.reduce((a, b) => a + b, 0);
for (const [name, list] of [['3D faces', from3d], ['flat grids', flatFull], ['overview', flatMini]]) {
  const got = list.filter((c) => c.st === 'available' && c.price).map((c) => +c.price).sort((a, b) => a - b);
  ck(got.length === dataPrices.length && got.every((v, i) => v === dataPrices[i]),
    `${name.padEnd(11)} price multiset identical to the data module (${got.length} priced niches)`);
}
{
  // The chips actually printed in the flat grids, read back out of the HTML.
  const chips = [...src.matchAll(/<span class="nprice [^"]*">\$([\d,]+)<\/span>/g)]
    .map((m) => +m[1].replace(/,/g, ''));
  const wanted = dataPrices.concat(dataPrices).sort((a, b) => a - b); // full grids + overview
  chips.sort((a, b) => a - b);
  ck(chips.length === wanted.length && chips.every((v, i) => v === wanted[i]),
    `rendered flat price chips = ${chips.length} (${N_AVAIL} per rendering × 2 renderings), all matching`);
}
ck(dataPrices.length === N_AVAIL, `${N_AVAIL} niches are available and priced (${dataPrices.length})`);
pass(`available inventory at list = ${money(AVAIL_TOTAL)}`);
ck(AVAIL_TOTAL === AVAIL_ANCHOR, `available total is ${money(AVAIL_ANCHOR)} (got ${money(AVAIL_TOTAL)})`);
{
  // Per-elevation sums are ANCHORED, not merely printed. A whole-cabinet total can stay
  // right while two elevations swap a niche between them; these four cannot.
  for (const f of FACE_ORDER) {
    const avail = WALLS[f].niches.filter(sellable);
    const sum = avail.reduce((a, n) => a + n.p, 0);
    const [wantN, wantSum] = PER_FACE_ANCHOR[f];
    ck(avail.length === wantN && sum === wantSum,
      `${FACE_META[f].label.padEnd(14)} ${wantN} available, ${money(wantSum)} (got ${avail.length}, ${money(sum)})`);
  }
}

// ── 6. THE SAFETY GATE: no price anywhere on an unsellable niche ──────────────
console.log('\nNo price is rendered for a sold or unpriced niche');
{
  const unsell = new Set(data.filter((n) => !sellable(n)).map((n) => n.ref));
  const nSold = data.filter((n) => n.st === 'sold').length;
  const nUnpriced = data.filter((n) => n.st === 'unpriced').length;
  ck(unsell.size === SHEET_TOTAL - N_AVAIL, `${unsell.size} niches are not sellable (${nSold} sold + ${nUnpriced} unpriced)`);
  const offenders = [];
  for (const [name, list] of [['3D', from3d], ['flat', flatFull], ['overview', flatMini]]) {
    for (const c of list) {
      if (!unsell.has(c.ref)) continue;
      if (/\$\s*[\d,]+/.test(c.html)) offenders.push(`${name} ${c.ref} renders a dollar figure`);
      if (c.price !== '') offenders.push(`${name} ${c.ref} carries data-price="${c.price}"`);
    }
  }
  ck(offenders.length === 0, `zero dollar figures across all ${unsell.size * 3} unsellable renderings${offenders.length ? ' — ' + offenders.slice(0, 6).join('; ') : ''}`);
  // aria-labels too: a screen reader must not read out a price either.
  const ariaBad = [...src.matchAll(/aria-label="(ECL-1-[^"]*)"/g)]
    .map((m) => m[1])
    .filter((l) => unsell.has(l.split(',')[0]) && /\$/.test(l));
  ck(ariaBad.length === 0, `zero dollar figures in the aria-labels of unsellable niches${ariaBad.length ? ' — ' + ariaBad.slice(0, 3).join('; ') : ''}`);
  // and every one of them is pattern-coded, not hue-coded
  const notMarked = [...from3d, ...flatFull].filter((c) => unsell.has(c.ref) && !/class="[^"]*st-(sold|unpriced)/.test(c.html));
  ck(notMarked.length === 0, 'every unsellable niche carries the dimmed/frosted st- class in both renderings');
}

// ── 6b. Materials: champagne everywhere, sold is DIMMED not BLACK ─────────────
// Operator ruling 2026-07-29: "black does not look good here" — the niches read as
// champagne-lit glass like the MVC page, and a sold niche is a dimmed, frosted
// champagne, never a solid black cell. Sold/available stay separated by BRIGHTNESS
// and PATTERN, never by hue (every hue on the page belongs to a price tier).
console.log('\nMaterials (champagne, per the operator ruling)');
{
  // The declaration block that begins at an exact selector string.
  const rule = (sel) => {
    const i = src.indexOf(sel);
    return i < 0 ? '' : src.slice(i, src.indexOf('}', i) + 1);
  };
  const CHAMPAGNE = /#f2dda6[\s\S]*#e2bd79[\s\S]*#cd9d58/;
  const flat = rule('\r\n  .n{border-radius:3px');
  const three = rule('\r\n  .n3{border:none');
  const sold = rule('\r\n  .st-sold,.st-unpriced{color');
  const face = rule('\r\n  .face{position:absolute');
  ck(CHAMPAGNE.test(flat), 'flat niche cell is the champagne ramp #f2dda6/#e2bd79/#cd9d58');
  ck(CHAMPAGNE.test(three), '3D niche front is the same champagne ramp');
  ck(/#b0a389[\s\S]{0,120}#786f5b/.test(sold),
    'sold / not-priced cells are the DIMMED champagne #b0a389→#786f5b, not black');
  ck(/repeating-linear-gradient\(135deg,rgba\(255,255,255,\.40\)/.test(sold),
    'sold / not-priced cells carry the frosted diagonal hatch (pattern, not hue)');
  ck(!/#1b1c20|#0e0f12/.test(src), 'the old near-black niche fill is gone from the page entirely');
  ck(/background:#15120d/.test(face), 'the mullion frame is near-black bronze (#15120d)');
  ck(/border:2px solid #8a7147/.test(face), 'the frame carries the brass trim line #8a7147');
}

// ── 6c. Price-chip contrast: every tier label clears WCAG AA (4.5:1) ──────────
console.log('\nPrice-chip contrast (WCAG AA, 4.5:1)');
{
  const lin = (c) => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
  const lum = (hex) => {
    let h = hex.replace('#', '');
    if (h.length === 3) h = h.split('').map((x) => x + x).join('');
    const [r, g, b] = [0, 2, 4].map((i) => lin(parseInt(h.slice(i, i + 2), 16) / 255));
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
  };
  const ratio = (a, b) => {
    const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);
    return (x + 0.05) / (y + 0.05);
  };
  let worst = 99, worstT = '';
  for (const t of TIERS) {
    const r = ratio(t.bg, t.fg);
    if (r < worst) { worst = r; worstT = t.l; }
    ck(r >= 4.5, `${t.l.padEnd(8)} ${t.fg} on ${t.bg} = ${r.toFixed(2)}:1`);
  }
  pass(`worst tier chip contrast ${worst.toFixed(2)}:1 (${worstT}) — all ${TIERS.length} clear AA`);
}

// ── 6d. Add-on toggles feed the card math (operator, 2026-07-29) ──────────────
console.log('\nBronze Scroll / Vase add-on toggles');
{
  const js = src.slice(src.lastIndexOf('<script>'));
  ck(new RegExp(`SCROLL = ${FEES.SCROLL}`).test(js), `the page carries SCROLL = ${FEES.SCROLL}`);
  ck(new RegExp(`VASE = ${FEES.VASE}`).test(js), `the page carries VASE = ${FEES.VASE}`);
  for (const [id, label] of [['scroll-on', 'Bronze Scroll'], ['vase-on', 'Vase with Ring']]) {
    const m = new RegExp(`<input type="checkbox" id="${id}"[^>]*>`).exec(src);
    ck(!!m, `${label} renders a checkbox #${id}`);
    ck(!!m && !/\bchecked\b/.test(m[0]), `${label} defaults to OFF (no checked attribute)`);
    ck(new RegExp(`addOn\\('${id}'\\)`).test(js), `${label} is read by the card math via addOn('${id}')`);
  }
  ck(/taxable \+= SCROLL;/.test(js) && /taxable \+= VASE;/.test(js),
    'each toggle adds its flat amount to the taxable add-on subtotal');
  ck(/tot \+= taxable \+ tx;/.test(js),
    'the add-on subtotal and its tax are both added to the card total');
  // E.C.F. must be 10% of the NICHE PRICE only. The one call site takes `price`, and
  // the add-on lines are appended to `tot` afterwards, so no add-on can ever be taxed.
  ck(/var price = \+d\.price, e = ecf\(price\), tot = price \+ e,/.test(js),
    'E.C.F. is computed once, from the niche price alone');
  ck(!/ecf\((?!price\))/.test(js), 'ecf() is never called on anything but the niche price');
  const scrollAt = js.indexOf('taxable += SCROLL'), ecfAt = js.indexOf('e = ecf(price)');
  ck(ecfAt > -1 && scrollAt > ecfAt, 'the add-ons are added AFTER the E.C.F. line, never into its base');
  ck(/'oc-qty', 'rec-qty', 'scroll-on', 'vase-on'/.test(js),
    'both toggles re-render the pinned card (and therefore its print block) on change');
  ck(/closest\('#card, \.tab, \.tbtn, \.fees'\)/.test(js),
    'clicking the fee footer does not unpin the card the toggles are updating');
}

// ── 6e. The uniform glass-front fee schedule (operator, 2026-07-31) ───────────
// "All glass front niches should have the same opening and closing and recording fee.
//  Also there is no inscription fee on any glass front niche. The opening and closing
//  fee is 875 and the recording fee is 235 same 10% ecf applies. There will be no tax
//  on a glass front niche unless its ecl and they add the vase and scroll"
//
// These are ASSERTED, not merely echoed from the module: the literal 875 / 235 / 0.1 /
// 0.104 are written out here so that changing ecl-niche-data.mjs alone fails this gate.
// ECL is the one glass-front surface that carries any tax, and only on the two bronze
// add-ons — hence the "nothing else is taxed" checks below.
console.log('\nGlass-front fee schedule (operator ruling 2026-07-31)');
{
  const js = src.slice(src.lastIndexOf('<script>'));
  ck(FEES.OC === 875, `module O&C is $875 (got ${money(FEES.OC)})`);
  ck(FEES.REC === 235, `module recording fee is $235 (got ${money(FEES.REC)})`);
  ck(FEES.ECF_RATE === 0.1, `module E.C.F. rate is 10% (got ${FEES.ECF_RATE * 100}%)`);
  ck(FEES.TAX === 0.104, `module add-on tax rate is 10.4% (got ${FEES.TAX * 100}%)`);
  ck(new RegExp(`Open &amp; Closing — \\$875 ea`).test(src), 'the fee footer prints Open & Closing $875 ea');
  ck(/Recording Fee — \$235 ea/.test(src), 'the fee footer prints Recording Fee $235 ea');
  ck(/OC = 875,/.test(js) && /REC = 235,/.test(js), 'the page carries OC = 875 and REC = 235');
  ck(/TAX = 0\.104/.test(js), 'the page carries TAX = 0.104');

  // No inscription fee exists on ANY glass-front niche — not as a line, not as a toggle.
  ck(!('INSCR' in FEES) && !('INSCRIPTION' in FEES), 'the module exports no inscription fee at all');
  ck(!/insc/i.test(js) || /no inscription fee/i.test(js),
    'the page script contains no inscription math');
  ck(!/id="insc[^"]*"/.test(src), 'the page renders no inscription input or toggle');
  ck(/Inscription<\/span>\s*\r?\n?\s*<span class="fv">none/.test(src),
    'the fee footer states explicitly that there is no inscription fee');

  // Tax base: the scroll and the vase, and nothing else.
  ck(/var taxable = 0;/.test(js), 'the tax base starts at zero and is built from add-ons only');
  const taxLines = [...js.matchAll(/taxable \+= (\w+);/g)].map((m) => m[1]).sort();
  ck(JSON.stringify(taxLines) === JSON.stringify(['SCROLL', 'VASE']),
    `only the scroll and the vase are taxable (found: ${taxLines.join(', ') || 'nothing'})`);
  ck(!/OC \* oc[\s\S]{0,200}taxable/.test(js) && !/taxable \+= (OC|REC|price|e)\b/.test(js),
    'neither the O&C, the recording fee, the niche price nor the E.C.F. is ever taxed');
  ck(/Sales Tax \(10\.4%\)/.test(js), 'the card labels the tax line at 10.4%');
  ck(/scroll and vase only/.test(src), 'the fee footer scopes the tax to the two add-ons');
}

// ── 6f. Price legibility (operator, 2026-07-31) ───────────────────────────────
// "the font size for the prices on the niche need to be increased right now they are
//  very hard to read". The chip is sized from its own cell's inline size, so a wide
//  niche gets a large price and the narrowest niche still fits inside its borders.
// The FLOOR is what matters: it must exceed the flat 10.5px / 7.5px this replaced.
console.log('\nPrice-chip legibility');
{
  const rule = (sel) => {
    const i = src.indexOf(sel);
    return i < 0 ? '' : src.slice(i, src.indexOf('}', i) + 1);
  };
  const flatChip = rule('\r\n  .nprice{');
  const threeChip = rule('\r\n  .n3p{');
  const grab = (r) => (/clamp\(([\d.]+)px,\s*([\d.]+)cqw,\s*([\d.]+)px\)/.exec(r) || []).slice(1).map(Number);
  const [fLo, , fHi] = grab(flatChip);
  const [tLo, , tHi] = grab(threeChip);
  ck(fLo >= 11 && fHi >= 15, `flat-grid price chip scales ${fLo}px–${fHi}px (was a flat 10.5px)`);
  ck(tLo >= 8.5 && tHi >= 12, `3D-face price chip scales ${tLo}px–${tHi}px (was a flat 7.5px)`);
  ck(/container-type:inline-size/.test(rule('\r\n  .n{border-radius:3px')),
    'the flat niche cell is a size container, so cqw resolves against the cell');
  ck(/container-type:inline-size/.test(rule('\r\n  .n3{border:none')),
    'the 3D niche front is a size container too');
  ck(/white-space:nowrap/.test(flatChip), 'a price never wraps inside its chip');
}

// ── 7. Print path ─────────────────────────────────────────────────────────────
console.log('\nPrint path');
{
  const views = (src.match(/id="wall-[SNWE]"/g) || []).length;
  ck(views === 4, `all four elevation views exist as static HTML (${views})`);
  ck(/\.wview\{display:none;\}/.test(src.replace(/\s+/g, '')) || /\.wview,\.view3d\{display:none/.test(src),
    'elevation views are hidden on screen and revealed by the tab / print rules');
  ck(/\.wview\{display:block!important/.test(src), 'print stylesheet forces every elevation visible without JS');
  ck(/body\.pv-sel \.wview\.printsel\{display:block!important/.test(src), 'print scope follows a highlighted niche');
  ck(/body\.pv-one \.wview\.active\{display:block!important/.test(src), 'print scope follows the active elevation tab');
  ck(/\.n\.sel\{outline:4px solid #c8540a/.test(src), 'a selected niche prints with the highlight ring');
  const scripts = (src.match(/<script/g) || []).length;
  ck(scripts === 1, `page has ${scripts} <script> block(s); none is needed to render the flat grids`);
}

// ── 7b. The pinned card must never cover the tab bar ──────────────────────────
console.log('\nPinned card vs the tab bar');
{
  // A pinned niche in a hidden view has a ZERO rect, and a card placed against zero
  // lands on the tab bar and eats the tab clicks. Found by driving the GOMN page, 2026-07-31.
  const js = src.slice(src.lastIndexOf('<script>'));
  ck(/function visibleTwin\(el\)/.test(js), 'the card places itself against a rendering that is actually laid out');
  ck(/var t = visibleTwin\(el\);/.test(js) && /if \(!t\) \{ card\.style\.left/.test(js),
    'and parks in its default corner when no rendering of the pinned niche is visible');
  ck(!/var r = el\.getBoundingClientRect\(\);\s*\r?\n\s*card\.style\.right = 'auto'/.test(js),
    'placeCard no longer measures the pinned element directly (the zero-rect path)');
}

// ── 8. House rules ────────────────────────────────────────────────────────────
console.log('\nHouse rules');
ck(/class="back-btn no-print" href="\.\.\/"/.test(src), '"← Quote Tool" back button in the header');
ck(/estimated from photographs/.test(src), 'the header says the geometry is estimated from photographs');
{
  // No niche dimensions anywhere: there is no fabrication drawing for ECL-1.
  const dims = [...src.matchAll(/\d+\s*(?:"|&quot;|″)\s*(?:x|×)\s*\d+/gi)].map((m) => m[0]);
  ck(dims.length === 0, `no niche dimensions rendered${dims.length ? ' — ' + dims.slice(0, 3).join(', ') : ''}`);
}
{
  // Exact prices only: no "$18.7K" style rounding anywhere.
  const rounded = [...src.matchAll(/\$\d+(?:\.\d+)?K/g)].map((m) => m[0]);
  ck(rounded.length === 0, `no rounded price labels${rounded.length ? ' — ' + rounded.join(', ') : ''}`);
}
ck(!/ELC-1/.test(src), 'the sheet\'s "ELC-1" typo does not reach the page');


// ── Movement runtime (ported from the COM map, sprint-10) ────────────────────
// The feel is generated from scripts/map-movement.mjs, so the only thing worth
// asserting here is that the page still CARRIES it: a build script edited to drop the
// interpolation would otherwise revert silently to cut transitions and no inertia, and
// nothing else on this page would notice. The two behavioural invariants are asserted
// too, because they are the ones a family sees go wrong: the tap detector's threshold
// must still be pointer TRAVEL, and inertia must not have widened the click-suppression
// window (a window that outlived the coast would swallow the next tap).
console.log('\nMovement runtime');
{
  const js = src.slice(src.lastIndexOf('<script>'));
  for (const [tok, what] of MOVEMENT_TOKENS) ck(js.indexOf(tok) > -1, what);
  const keys = ["yaw","pitch","zoom","lift"];
  const m = /var CAM_KEYS = (\[[^\]]*\])/.exec(js);
  ck(!!m && JSON.stringify(JSON.parse(m[1])) === JSON.stringify(keys),
    `an eased transition carries the WHOLE camera: ${keys.join(', ')}` +
    (m ? ` (page: ${m[1]})` : ' — CAM_KEYS not found'));
  ck(/moved <= 8/.test(js), 'the tap detector still keys off POINTER TRAVEL (moved <= 8)');
  ck(/suppressUntil = performance\.now\(\) \+ 450;/.test(js),
    'the click-suppression window is still a flat 450 ms and is not tied to camera motion');
  ck(!/suppressUntil[^;]*(vYaw|vPitch|glideRaf|camT)/.test(js),
    'nothing about the glide can extend the suppression window');
  ck(/releaseGesture\(moved\);/.test(js), 'the release reads pointer travel and nothing else');
  ck(/stopGlide\(\);\s*\/\/ any touch interrupts/.test(js), 'a pointerdown stops the camera');
  ck(/ev\.preventDefault\(\); stopGlide\(\);/.test(js), 'the wheel stops the camera too');
  ck(!/function floorPoint\(/.test(js), 'no floor-travel on an orbit-a-cabinet page (presets + inertia only)');
}

console.log(failures ? `\nRESULT: ${failures} FAILURE(S)` : '\nRESULT: PASS — 0 mismatches');
process.exit(failures ? 1 : 0);
